version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8088:80"
        # dependence
        depends_on:
            - "php"
        # volumes
        volumes:
            - "/www/php-nginx-compose/conf.d:/etc/nginx/conf.d"
            - "/www/php-nginx-compose/html:/usr/share/nginx/html"
        networks:
            - app_net
        container_name: "compose-nginx"
        links:
            - php
    php:
        build: ./php-mysqli
        image: php:7.4-fpm-mysqli
        ports:
            - "9000:9000"
        volumes:
            - "/www/php-nginx-compose/html:/var/www/html:rw"
            - "/www/php-nginx-compose/html/messages:/var/log/messages"
        networks:
            - app_net
        container_name: "compose-php"
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
           - app_net
        container_name: "compose-mysql"
networks:
    app_net:
        driver: bridge
